[2024-05-31T03:50:55.692+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T03:50:55.729+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-31T03:32:54.698754+00:00 [queued]>
[2024-05-31T03:50:55.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-31T03:32:54.698754+00:00 [queued]>
[2024-05-31T03:50:55.742+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 9
[2024-05-31T03:50:55.757+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): is_city_api_ready> on 2024-05-31 03:32:54.698754+00:00
[2024-05-31T03:50:55.766+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'is_city_api_ready', 'manual__2024-05-31T03:32:54.698754+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpewpuaui_']
[2024-05-31T03:50:55.770+0000] {standard_task_runner.py:91} INFO - Job 169: Subtask is_city_api_ready
[2024-05-31T03:50:55.773+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=869) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-31T03:50:55.774+0000] {standard_task_runner.py:63} INFO - Started process 871 to run task
[2024-05-31T03:50:55.837+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.is_city_api_ready manual__2024-05-31T03:32:54.698754+00:00 [running]> on host cd9caf1c47f0
[2024-05-31T03:50:55.944+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='is_city_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T03:32:54.698754+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T03:32:54.698754+00:00'
[2024-05-31T03:50:55.950+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T03:50:55.972+0000] {http.py:137} INFO - Poking: /v1/geo/cities/Q25282
[2024-05-31T03:50:55.986+0000] {base.py:84} INFO - Using connection ID 'city_map_api_connection' for task execution.
[2024-05-31T03:50:56.564+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T03:50:56.565+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T03:50:56.581+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=is_city_api_ready, run_id=manual__2024-05-31T03:32:54.698754+00:00, execution_date=20240531T033254, start_date=20240531T035055, end_date=20240531T035056
[2024-05-31T03:50:56.632+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T03:50:56.658+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T03:50:56.661+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
