[2024-05-31T16:21:35.329+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T16:21:35.355+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.transform_data_city_api manual__2024-05-31T11:14:41.858816+00:00 [queued]>
[2024-05-31T16:21:35.367+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.transform_data_city_api manual__2024-05-31T11:14:41.858816+00:00 [queued]>
[2024-05-31T16:21:35.368+0000] {taskinstance.py:2306} INFO - Starting attempt 8 of 13
[2024-05-31T16:21:35.387+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_city_api> on 2024-05-31 11:14:41.858816+00:00
[2024-05-31T16:21:35.398+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1287) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-31T16:21:35.400+0000] {standard_task_runner.py:63} INFO - Started process 1289 to run task
[2024-05-31T16:21:35.398+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'transform_data_city_api', 'manual__2024-05-31T11:14:41.858816+00:00', '--job-id', '394', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpwpe33vzv']
[2024-05-31T16:21:35.402+0000] {standard_task_runner.py:91} INFO - Job 394: Subtask transform_data_city_api
[2024-05-31T16:21:35.474+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.transform_data_city_api manual__2024-05-31T11:14:41.858816+00:00 [running]> on host cd9caf1c47f0
[2024-05-31T16:21:35.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='transform_data_city_api' AIRFLOW_CTX_EXECUTION_DATE='2024-05-31T11:14:41.858816+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-31T11:14:41.858816+00:00'
[2024-05-31T16:21:35.593+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T16:21:35.636+0000] {python.py:237} INFO - Done. Returned value was: {'file_name': 'city_data_31-05-2024.csv', 'wiki_id': 'Q25315', 'latitude': 10.937, 'longitude': 108.15778}
[2024-05-31T16:21:35.636+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T16:21:35.671+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=transform_data_city_api, run_id=manual__2024-05-31T11:14:41.858816+00:00, execution_date=20240531T111441, start_date=20240531T162135, end_date=20240531T162135
[2024-05-31T16:21:35.696+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T16:21:35.730+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T16:21:35.734+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
