[2024-06-01T04:50:07.941+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T04:50:07.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:42:53.478399+00:00 [queued]>
[2024-06-01T04:50:07.978+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:42:53.478399+00:00 [queued]>
[2024-06-01T04:50:07.979+0000] {taskinstance.py:2306} INFO - Starting attempt 5 of 10
[2024-06-01T04:50:07.994+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_tasks.is_api_weather_api_ready> on 2024-06-01 04:42:53.478399+00:00
[2024-06-01T04:50:08.004+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4380) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T04:50:08.007+0000] {standard_task_runner.py:63} INFO - Started process 4382 to run task
[2024-06-01T04:50:08.005+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'group_tasks.is_api_weather_api_ready', 'manual__2024-06-01T04:42:53.478399+00:00', '--job-id', '523', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmpo1n73ny4']
[2024-06-01T04:50:08.008+0000] {standard_task_runner.py:91} INFO - Job 523: Subtask group_tasks.is_api_weather_api_ready
[2024-06-01T04:50:08.079+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:42:53.478399+00:00 [running]> on host cd9caf1c47f0
[2024-06-01T04:50:08.229+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='group_tasks.is_api_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T04:42:53.478399+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T04:42:53.478399+00:00'
[2024-06-01T04:50:08.232+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T04:50:08.247+0000] {http.py:137} INFO - Poking: /data/2.5/weather?lat=10.937&lon=108.15778&appid=cb9774016f254a4cb1aa6516bf401afa
[2024-06-01T04:50:08.262+0000] {base.py:84} INFO - Using connection ID 'weather_map_api_connection' for task execution.
[2024-06-01T04:50:08.852+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-01T04:50:08.853+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T04:50:08.869+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=group_tasks.is_api_weather_api_ready, run_id=manual__2024-06-01T04:42:53.478399+00:00, execution_date=20240601T044253, start_date=20240601T045007, end_date=20240601T045008
[2024-06-01T04:50:08.906+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T04:50:08.940+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-01T04:50:08.943+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
