[2024-06-01T04:40:27.784+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-01T04:40:27.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:21:04.663663+00:00 [queued]>
[2024-06-01T04:40:27.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:21:04.663663+00:00 [queued]>
[2024-06-01T04:40:27.814+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 12
[2024-06-01T04:40:27.828+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): group_tasks.is_api_weather_api_ready> on 2024-06-01 04:21:04.663663+00:00
[2024-06-01T04:40:27.836+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4014) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-01T04:40:27.838+0000] {standard_task_runner.py:63} INFO - Started process 4016 to run task
[2024-06-01T04:40:27.836+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'my_weather_workflow_DAG_v04', 'group_tasks.is_api_weather_api_ready', 'manual__2024-06-01T04:21:04.663663+00:00', '--job-id', '487', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmppyknhckx']
[2024-06-01T04:40:27.839+0000] {standard_task_runner.py:91} INFO - Job 487: Subtask group_tasks.is_api_weather_api_ready
[2024-06-01T04:40:27.898+0000] {task_command.py:426} INFO - Running <TaskInstance: my_weather_workflow_DAG_v04.group_tasks.is_api_weather_api_ready manual__2024-06-01T04:21:04.663663+00:00 [running]> on host cd9caf1c47f0
[2024-06-01T04:40:28.032+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Khang' AIRFLOW_CTX_DAG_ID='my_weather_workflow_DAG_v04' AIRFLOW_CTX_TASK_ID='group_tasks.is_api_weather_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-06-01T04:21:04.663663+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-01T04:21:04.663663+00:00'
[2024-06-01T04:40:28.034+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-01T04:40:28.047+0000] {http.py:137} INFO - Poking: /data/2.5/weather?lat=10.937&lon=108.15778&appid=cb9774016f254a4cb1aa6516bf401afa
[2024-06-01T04:40:28.061+0000] {base.py:84} INFO - Using connection ID 'weather_map_api_connection' for task execution.
[2024-06-01T04:40:28.312+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-01T04:40:28.313+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-01T04:40:28.338+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=my_weather_workflow_DAG_v04, task_id=group_tasks.is_api_weather_api_ready, run_id=manual__2024-06-01T04:21:04.663663+00:00, execution_date=20240601T042104, start_date=20240601T044027, end_date=20240601T044028
[2024-06-01T04:40:28.375+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-01T04:40:28.407+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-01T04:40:28.410+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
